### ISSUE TITLE
Not opening in the filepath folder

### ISSUE THREAD

**Issue by egabrum** [ipatalas/vscode-conemu#1]
> Note: If the command cannot infer filepath from current document (untitled unsaved files) it opens the project folder.

I try to use it with titled and saved documents but, every time, if opens ConEmu in the project folder, not in the folder where the document lives. This is quite frustrating.

Do you have any idea why this might be happening?
thanks

**Comment by ipatalas** [comment]
Hi

First of all, which version do you use? There has been an update yesterday which fixed a very similar bug.

How do you trigger the command? Please try a keyboard shortcut (there's no default so you have to set it up yourself - the command name is `vscode.conemu`) and context menu on file in explorer in on a tab. All of them trigger the same command, but the handling is slightly different under the hood.
Let me know if any option works.
If all fails we'll figure it out differently.

Regards,
Irek

**Comment by egabrum** [comment]
I use 1.0.1 (February 26, 2017)

I trigger it using different methods: 
- the Titlebar Icon.
- Right click on the tab of the editor and 'Open in ConEmu'
- Right click on file explorer and 'Open in ConEmu'
('Open in Command Prompt' goes to the right folder)
- Using the keybinding:
`{ "key": "shift+alt+c",  "command": "vscode.conemu", "when": "!terminalFocus" },`

**Comment by ipatalas** [comment]
Can you tell me the path of the project and the file you're trying to open? Does it contain any special characters?
Does the extension work for you in any circumstances or is it always opening the project's folder?

**Comment by egabrum** [comment]
`C:\Python27\Lib\site-packages\_pytest\skipping.py`
Instead it opens to `C:\Users\myUserName`

When I use the 'Start any shell' extension, it goes to the right path.

My Startup config in ConEmu:
`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%`

**Comment by ipatalas** [comment]
Okay.. so maybe it's not an issue with the extension itself.

Let's try calling ConEmu directly as my extension does it to see if you can reproduce the problem.
Execute the following command in your ConEmu directory:
`ConEmu64.exe -dir "C:\Python27\Lib\site-packages\_pytest" -Single`

Where does it open? In specified directory or your profile?

Can you please also try removing the `-new_console:d:%USERPROFILE%` part from your startup config just to see if it changes anything?

**Comment by egabrum** [comment]
> Can you please also try removing the -new_console:d:%USERPROFILE% part from your startup config just to see if it changes anything?

That did the trick,thanks!

**Comment by ipatalas** [comment]
Great! Glad it helped. 

I don't why you had this part in your startup config. It's not a default to my knowledge and doesn't make much sense to be honest.

Cheers!

**Comment by egabrum** [comment]
> I don't why you had this part in your startup config. It's not a default to my knowledge and doesn't make much sense to be honest.

You're right. I must have added it long time ago to keep Cmder from starting in the Cmder folder.
