### ISSUE TITLE
ConEmu killed when I close/reload VS Code

### ISSUE THREAD

**Issue by egabrum** [ipatalas/vscode-conemu#2]
I like vscode-conemu, specially the reuseInstance and showTitlebarIcon features, but every time I close or reload VS Code, it kills my ConEmu terminals, reverting to old cmd.exe

This does not happen with other extensions such as "Launcher" or "Start any Shell", so I'd love if vscode-conemu matched that.

**Comment by ipatalas** [comment]
Thanks for feedback. You're right.. had the same issue in my other extension for Total Commander. Forgot to improve this as well back then.

Check v1.0.2 and let me know if it fixes the problem for you (it does for me).

**Comment by egabrum** [comment]
Fixed! ...and quick too. Thanks.
