### ISSUE TITLE
20170503 Upgraded to new version. Launch ConEmu Stopped working

### ISSUE THREAD

**Issue by MikeAustin71** [ipatalas/vscode-conemu#3]
After 20170503 Upgrade, lanuch ConEmu from menu failed. Pop up window error says "Windows cannot find '-dir'. Make sure you typed the name correctly, and then try again."

Everything was working fine before the 20170503 Upgrade

**Comment by ipatalas** [comment]
Do you get the same error when executing from command palette or toolbar icon?

**Comment by MikeAustin71** [comment]
Error generated with both toolbar icon, right click file in project window and key combination Ctrl+Shift+C. Running Windows 10 - latest updates.

**Comment by bjarte** [comment]
I have the same problem with 
- Windows 7
- VS Code version 1.11.2
- ConEmu Launcher version 1.0.2
- ConEmu version 170402.x64 (beta)
- ConEmu version 161206.x64 (stable)

I tried to open ConEmu by
- Clicking the toolbar button
- Right-clicking a file and selecting "Open in ConEmu"
- Keyboard shortcut ALT+SHIFT+C

All approaches give error message "Windows cannot find '-dir'. Make sure you typed the name correctly, and then try again."

**Comment by ipatalas** [comment]
I wasn't able to reproduce this issue for now. I will get back to it on Sunday. Unfortunately I'm away for two days and don't have access to any computer. 

For now I can only suggest going back to older version for couple of days. Here is an instruction how to do that: http://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline

The link for older version is https://ipatalas.gallery.vsassets.io/_apis/public/gallery/publisher/ipatalas/extension/vscode-conemu/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

You might need to uninstall current version before. Really sorry for inconvenience guys. Making a release just before leaving wasn't the best idea.

**Comment by bjarte** [comment]
Thanks for the tip, but it doesn't work for me, I'm afraid.

When I install the 1.0.1 vsix file, VS Code immediately upgrades the extension to 1.0.2, even when I have extensions.autoUpdate set to false. I'm just disabling the extension for now.

 I really appreciate the work you put into the extension, thanks a lot!

**Comment by ipatalas** [comment]
Well... Can't help more via phone I'm afraid. Too bad it doesn't work but also strange that you get that auto update in vscode. I think it shouldn't work that way.
We need to wait until I'm back then. I will still need some help from you to reproduce that issue cause it didn't happen on my machine. I'll get back to you probably on Sunday. 
Take care!

**Comment by ipatalas** [comment]
@MikeAustin71 @bjarte 

Ok, I was able to reproduce the issue on a VM with clean Windows. It turned out there was a problem only when there was a space in path to ConEmu which wasn't the case on my machine but was on a default installation (in Program Files).
Anyway I think I found a solution which does the job.
Please update to 1.0.3 and let me know if you still experience this issue.

**Comment by MikeAustin71** [comment]
Works Great! Thank You! Working on VS Code 1.12.1, ConEmu 170402 Preview, Windows 10.  Thank you for writing a great App! This really helps!

**Comment by bjarte** [comment]
Works here too. Thank you!

**Comment by app-js** [comment]
With
VS Code version 1.13.0
Windows 7
(64bit: W7 and ConEmu)
and setting:
"ConEmu.path": "\\"C:\\\Program Files\\\ConEmu\\\""
i got:
"ConEmu path is invalid, please correct it."

The path is correct, any help?

**Comment by ipatalas** [comment]
@app-js it has to be a full path to ConEmu executable so you should rather try:

`"ConEmu.path": "C:\\Program Files\\ConEmu\\ConEmu64.exe"` (or ConEmu.exe for 32-bit version)
