### ISSUE TITLE
"command failed" in VSCode Output although it works as expected

### ISSUE THREAD

**Issue by safizn** [ipatalas/vscode-conemu#4]
Hi thanks for the plugin. I got annoyed trying to figure out how to hide the message that came revealing in the `OUTPUT` (Ctrl+Shift+U) in VSCode: 
```
Command failed: "c:\Program Files\ConEmu\ConEmu64.exe" -dir c:\githubRepository -NoSingle
^C
^C
```
The issue is that it pops-up the `Output/Problems` bar each time I run `Open In ConEmu` from context menu. 
Tried to suppress it through VSCode settings without success: 
```
    "ConEmu.reuseInstance": false,
    "ConEmu.path": "c:\\Program Files\\ConEmu\\ConEmu64.exe",
    "problems.autoReveal": false,
```

Could you maybe add a setting that determines whether to show output of the extension ?

## Versions: 
**VSCode**
Version: 1.32.0-insider (system setup)
Commit: c23e8995f6e31b3540e0a2c3d4fdc58e6d7cba53
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**ConEmu**
1.0.4

**Comment by safizn** [comment]
If you could make this https://github.com/ipatalas/vscode-conemu/blob/225a069c9ef7840aa3b115b121e69d9b75bb4ac8/src/extension.ts#L42 optional through VSCode settings.json

**Comment by safizn** [comment]
By the way, when terminating the ConEmu window, the child process throws an error. Which is inconvenient.

**Comment by ipatalas** [comment]
> ```
> Command failed: "c:\Program Files\ConEmu\ConEmu64.exe" -dir c:\githubRepository -NoSingle
> ^C
> ^C
> ```
> The issue is that it pops-up the `Output/Problems` bar each time I run `Open In ConEmu` from context menu.

Which context menu? In Explorer panel or the tab context menu?
I'm not getting those in either of them but I actually am getting the same error after I close ConEmu window.
I'll try to investigate what may be the root cause. For now I will accept your PR. Seems reasonable not to show it by default.
