### ISSUE TITLE
Idea for improvement: Add ability to specify ConEmu Task for specific console startup

### ISSUE THREAD

**Issue by j-byrnes** [ipatalas/vscode-conemu#6]
Hello,
Thank you for the extension, and love using it.  I was wondering if we'd be able to add a setting to specify a specific ConEmu Task to use for execution using/adding the "-Run" [command line argument](https://conemu.github.io/en/ConEmuArgs.html) like the following:

`"c:\Program Files\ConEmu\ConEmu64.exe" -Dir "c:\Users\tuser\Documents\Scripts\MISC" -run {Shells::PowerShell (Admin)}`

I do a bunch of PowerShell scripting using vscode and find myself avoiding the internal console most of the time and my ConEmu startup task opens 2 console windows (which I need for my other operations work).  

Either way, I really appreciate the extension.

**Comment by j-byrnes** [comment]
I submitted a pull request with changes that appear to allow the specification of -Run Options #7

**Comment by ipatalas** [comment]
Resolved by #7
